### ISSUE TITLE
Slider with breakpoints goes back to first slide when adding a new slide

### ISSUE THREAD

**Issue by auraesteban** [Splidejs/react-splide#3]
Hello!

I'm currently doing a slider with dynamic slides. I've followed the example here: https://splidejs.github.io/react-splide/ (really liking this package btw ✨)

When I add a new slide, the position is retained. However, when the slider options has `breakpoints` included, adding a new one makes it return to the start. It would be nice if position is retained too.

![splide js](https://user-images.githubusercontent.com/10233609/88450357-f92f8c00-ce80-11ea-9238-e7008990ac00.gif)

Here is a sample of my code:
https://codesandbox.io/s/splide-with-breakpoints-k57vw

**Comment by NaotoshiFujita** [comment]
Hi, thank you for your report!

I've modified the code and the position should not be reset in the latest version:
https://codesandbox.io/s/splide-with-breakpoints-bexbr

**Comment by auraesteban** [comment]
That was quick! Confirming that this has been resolved. Thank you. 👍
