### ISSUE TITLE
`?.` Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by sapkra** [Splidejs/react-splide#30]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.6.5

### Description

I only know the `?.` syntax from TypeScript and I think that's the issue here.

```console
ERROR in /node_modules/@splidejs/react-splide/dist/js/react-splide.esm.js 2449:16
Module parse failed: Unexpected token (2449:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
|   go(control) {
>     this.splide?.go(control);
|   }
|   getSlides() {
```

### Steps to Reproduce

1. Install current react-splide version
2. Try to build it with webpack using es modules

### Expected Behaviour

Should build without error

**Comment by NaotoshiFujita** [comment]
It's not a TypeScript specific feature.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

Webpack 5 supports the syntax.
https://github.com/webpack/webpack/issues/10227

**Comment by sapkra** [comment]
Mhh, okay interesting and good to know. But for more context: This error appeared in the currect storybook version 6.3.12 which theoretically use webpack 5.

**Comment by NaotoshiFujita** [comment]
What do you mean "theoretically"? Storybook supports both webpack 4 and 5, and the default version is still 4.

**Comment by sapkra** [comment]
Ohh ok sorry, I thought they switched to v5 in general. I'm sorry for the misunderstanding. At least we found the source of the problem.

**Comment by NaotoshiFujita** [comment]
😎👍

**Comment by dimaninc2** [comment]
I use the plugin with nextjs v11 which uses webpack 5, but i have the error
node v12.19.0

**Comment by NaotoshiFujita** [comment]
If so, it's fatal for all nextjs users. You should report the bug to nextjs.

**Comment by dimaninc2** [comment]
i've also installed `@babel/plugin-proposal-optional-chaining`  and created `.babelrc` with following contents:
```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

and this didn't help

**Comment by NaotoshiFujita** [comment]
It's one of the solution for webpack4 to recognize the optional chaining. Webpack 5 does not require it since it uses the latest acorn under the hood.

**Comment by jindada** [comment]
Excuse me how to use `react-splide` with `webpack4`

```js
{
  "plugins": [
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```
this didn't help

**Comment by dimaninc2** [comment]
nextjs authors told me that "Next.js already supports optional chaining but node_modules are not compiled using Babel."

**Comment by NaotoshiFujita** [comment]
Ah, nextjs does not support transpiling node modules. It sounds very inconvenient.
https://github.com/vercel/next.js/issues/706

Okay. I'll think about it.

**Comment by NaotoshiFujita** [comment]
I transpiled the chaining syntax(^0.6.7).

**Comment by dimaninc2** [comment]
thanks, mate!

**Comment by NaotoshiFujita** [comment]
👍
