### ISSUE TITLE
Unable to load images for cloned slides in loop mode when using Skeletons

### ISSUE THREAD

**Issue by Doesntmeananything** [Splidejs/react-splide#32]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.6.16

### Description

Hi! First of all, thanks for the great library.

I've stumbled upon an issue when using Splide with a skeleton component for showing a loading state for images. Generally, a Skeleton is a placeholder element that gets hidden when an `onload` event of the wrapped `img` element is fired. In this case, I'm observing that the cloned elements remain stuck in loading state, which means that `onload` isn't triggered. This is especially noticeable when using `autoWidth: true` and `focus: Center`, where you can see that the first cloned image on the screen isn't loading.

![image](https://user-images.githubusercontent.com/34657799/144476593-b6380261-2a50-43c4-b868-9385de2ea4a8.png)

I understand that this not a core issue of the library, but I was wondering if there's a more or less official way to work around this problem, since using Skeletons for images is pretty common.

### Reproduction Link

https://codesandbox.io/s/distracted-shape-7q5fb?file=/src/App.tsx

### Steps to Reproduce

1. Set Splide options to
```js
type: "loop",
autoWidth: true,
focus: "center",
``` 
2. Have a Skeleton component that wraps an image element and gets hidden when an `onload` event of the image is triggered.
3. Use the Skeleton component in `SplideSlide`
4. Observe cloned elements not changing their loading state

### Expected Behaviour

Cloned elements with Skeletons are able to change their state based on the events of the children elements.

**Comment by Doesntmeananything** [comment]
Looking at this further, I think this may be a general limitation of the library, where the clones are snapshotted from the actual React components and then remain as static elements, unless something triggers a re-mount to start the snapshotting process again.

I understand the reason behind such implementation, but it does ultimately strike me as limiting, since there's no convenient way in loop mode to make clones truly reactive.

For now, triggering a force refresh of the slider when the non-cloned elements are firing `onload` does help, although I do lose certain niceties like animated transitions.

If there's a better way to do this or if you think that something can be done to accommodate this behaviour (like having virtualised clones, etc.), I'd be glad to provide any help I can!

**Comment by NaotoshiFujita** [comment]
Hi, Doesntmeananything.

As you already know, this is the inevitable design limitation. Clones are not reactive since Splide duplicates slides by native nodes, not by the react component. To make them reactive, we should create a slider from scratch under the react framework instead of just wrapping a vanilla library.

One solution is just switching Splide to other libraries made with React. If the reactivity is really important, you should consider that as one of options.

Another solution is solving the transition issue you are facing. Because the `refresh()` repositions the slider to the current index, the active transition is canceled. You can avoid it by postponing `refresh()` until the transition ends.

```js
let shouldRefresh;

// Checks the slider state in the onload callback
if ( splide.is( Splide.STATES.MOVING ) ) {
  shouldRefresh = true;
} else {
  splide.refresh();
}

// Processes the postponed refresh if necessary
splide.on( 'moved', () => {
  if ( shouldRefresh ) {
    splide.refresh();
    shouldRefresh = false;
  }  
} );
```

Note that the `refresh()` is a costly task. I did not test it but I think calling `update` may be enough in your case:
```js
splide.refresh();
// to
splide.emit( 'update' );
```

**Comment by Doesntmeananything** [comment]
Thank you for the useful tips!

I will look into an alternative (even though I'm very happy with Splide otherwise :cry: ). Something like https://swiperjs.com/ seems to support my use case with React.
