### ISSUE TITLE
import_splide2.Splide is not a constructor 

### ISSUE THREAD

**Issue by nqhung291** [Splidejs/react-splide#33]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.6.18

### Description

I cannot use react-splide version 0.6.18 due to import_splide2.Splide is not a constructor 
![image](https://user-images.githubusercontent.com/32951928/150065504-aa008247-290e-4911-b30b-7720d064cf87.png)

### Reproduction Link

https://codesandbox.io/s/react-splide-bug-nn1yf?file=/src/App.js

### Steps to Reproduce

1.
2.
...

### Expected Behaviour

Splide works

**Comment by NaotoshiFujita** [comment]
I've updated the package. Can you try the v0.6.19?
