### ISSUE TITLE
Thumbnails has a time delay to apply active class and is in the middle of the thumbnails

### ISSUE THREAD

**Issue by RodrigoTomeES** [Splidejs/react-splide#35]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.6.20

### Description

Thumbnails has a time delay to apply active class and is in the middle of the thumbnails. You can see it in the video:

https://user-images.githubusercontent.com/13077343/160638889-3e03fd15-6e8d-46d2-9c8a-a2855185d863.mov

Also you can see this error in the example code:

https://user-images.githubusercontent.com/13077343/160640642-04dd8425-6e6c-4c2c-95a8-53f36fefef31.mov

### Steps to Reproduce

1. Run your example code https://github.com/Splidejs/react-splide/blob/master/examples/src/js/components/ThumbnailsExample.tsx

### Expected Behaviour

That applying the active class is instantaneous as in the first thumbnails.

**Comment by NaotoshiFujita** [comment]
Enable `updateOnMove` option:
https://splidejs.com/guides/options/#updateonmove

**Comment by RodrigoTomeES** [comment]
@NaotoshiFujita Hi thanks! it works
