### ISSUE TITLE
how to hide first and last arrow "react-splide"

### ISSUE THREAD

**Issue by Learning-X** [Splidejs/react-splide#36]
But how do we do this in react-splide? It's hard to believe that there is no solution? Any work around to hide next-Arrow and prev-Arrow when first/last slide is active for react-splide? Thanks in advance!

_Originally posted by @Learning-X in https://github.com/Splidejs/splide/discussions/471#discussioncomment-2471181_

**Comment by NaotoshiFujita** [comment]
This has been already answered. Add styles to the `disabled` pseudo-class as you like.
https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled
