### ISSUE TITLE
Image disappears in the last slide (slide becomes blank) when it moves left

### ISSUE THREAD

**Issue by mvice21** [Splidejs/react-splide#37]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.6.20

### Description

I use React Splide with these options:

```
const options = {
    type: "loop",
    autoplay: true,
    pauseOnHover: false,
    arrows: false,
    pagination: false,
    width: "100%",
    height: "100%",
    interval: 3500,
    speed: 1500,
  }
```

And I notices that as soon as the last slides starts to move left an image in the slide becomes blank. Not the slide itself because I still can see text inside. Also the first slides that comes from the right also has blank image. Here is the gif I made: https://imgur.com/a/u1SGtNU
I tried to reduce the rewindSpeed but it didn't help.

P.S. I also noticed that if I give the last slider some backround color then it would ignore that CSS rule. But when it moves left it would change it's color. For example, if I set background color for every 2nd child of all slides (I have 6 slides in total, but it doesn't work with nth-child(2)):

```
.slide {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;

  &:nth-child(2) {
    background-color: tomato;
  }
}
```

then I would get this: https://imgur.com/a/6nJ9yIz

I think the last slide loses it's is-visible class as soon as it starts to move.

### Steps to Reproduce

.

### Expected Behaviour

.

**Comment by NaotoshiFujita** [comment]
Splide generates clones to loop the slider. When you start dragging on the first (or last) slide, it reculucutates each visibility and the active slide loses `is-visible` since it's out of viewport (a bit).

Why do you need to rely on `is-visible`?

**Comment by mvice21** [comment]
I don't rely on it. I just thought the problem was with the `is-visible` class. Anyway as you can see [here](https://imgur.com/a/u1SGtNU) the slider works a bit strange

**Comment by NaotoshiFujita** [comment]
Do you mean an image desappears in just a simple loop slider?

If so, the issue is not reproductive:
https://codesandbox.io/s/37-ejc5s

Please fork and reproduce your issue on it.
