### ISSUE TITLE
Thumbnail slider -> How to get current slide number ? 

### ISSUE THREAD

**Issue by namOota** [Splidejs/react-splide#38]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.6.20

### Description

I would like to seek help in finding the current slide

Usecase: I am using thumbnail slider
<img width="800" alt="image" src="https://user-images.githubusercontent.com/80577995/161295277-4bb02832-ce43-44c5-8e8e-34b7f5543dba.png">

I am using thumb slider as category and main slider to show the products related to that category [API driven]. 
API calls for all the available categories is getting triggered at once, which is not excepted, Ideally when user selects a particular category then api call inside that active slide should fetch the required data and show it to the user.

So here I am struggling to find out which is the active slide so that I can only then enable the contents of the slide and make an api call.

```
<Splide
        ref={(slider) => (slider2.current = slider)} // **Thumbnail Slider which holds categories like breakfast, lunch dinner..etc**
        options={SPLIDE_OPTIONS_thumb}
      >
        {categoryList.map((category, key) => (
          <li
            className="outline-none bg-white bg-gradient-to-l from-gray-100 text-center day py-1 splide__slide"
            key={key}
          >
            <div className="text-day uppercase">{category?.name}</div>
          </li>
        ))}
      </Splide>

      <Splide
        ref={(slider) => (slider1.current = slider)} // **Main slider used to show fetched Items**
        options={SPLIDE_OPTIONS_show}
        nextSlide={() => alert("manja")}
      >
        {daysList.map(
          (category, key) =>
            slider2.current === slider1.current && ( // => Here I am trying to check if the both the sliders are pointing to same slide and then show CategoryView component to make the required api call and show related products
              <li className="py-4 splide__slide" key={key}>
                <CategoryView dateInfo={category} id={id} />
              </li>
            )
        )}
      </Splide>
```

### Steps to Reproduce

1. Install nextjs / react project
2. npm i @splidejs/react-splide
3. how to get current slide number from both the slider ?

### Expected Behaviour

Need to get current slide number from both the thumbnail and main slider so that the we can only load that relevant page rather than fetching every data at once.

**Comment by NaotoshiFujita** [comment]
https://github.com/Splidejs/splide/discussions/731
