### ISSUE TITLE
Version 0.7.0 is broken with NextJS

### ISSUE THREAD

**Issue by TomSmedley** [Splidejs/react-splide#39]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.7.0

### Description

```
SyntaxError: Cannot use import statement outside a module

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///C:/Users/toms/Documents/Projects/GitHub/node_modules/%20(splidejs/react-splide/dist/js/react-splide.esm.js (2526)
Object.compileFunction
node:vm (352:18)
wrapSafe
node:internal/modules/cjs/loader (1032:15)
```

### Steps to Reproduce

1. Install NextJS
2. Install React-Splide
3. Error

### Expected Behaviour

Should load the module like it did previously.

**Comment by NaotoshiFujita** [comment]
Can you try 0.7.1?

**Comment by TomSmedley** [comment]
Thank you the latest version `0.7.2` works!
