### ISSUE TITLE
Updated to React 18 & @types/react 18

### ISSUE THREAD

**Issue by kno-raziel** [Splidejs/react-splide#40]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.7.4

### Description

I was able to integrate your library successfully with **React 17 &  @types/react 17 in a Nextjs project**, but today I have updated to 18 version and the following issue started to appear during build, I believe is related to the fact that the[ children prop is not longer implicit](https://twitter.com/reactjs/status/1512453969490108418).  

Right now I not sure how to solve this issue, and any direction would be great. 

Thanks. 

![image](https://user-images.githubusercontent.com/8211946/162636491-bde9284d-daf5-4310-af66-c78fc32fcbca.png)

### Steps to Reproduce

1. Any working project with React Splide
2. Update dependecies of react and types to 18.
...

### Expected Behaviour

Have a successful build using typescript as if with React 17 version.

**Comment by NaotoshiFujita** [comment]
Can you try v0.7.5?

**Comment by kno-raziel** [comment]
@NaotoshiFujita thanks using the new version fix this issue.

For anyone wondering about the releases versions you can find them in the npm. 

![image](https://user-images.githubusercontent.com/8211946/162781310-582579b0-cffb-423d-8b0f-d75432e4b1e5.png)

It would be nice to have that info on the repo other than that thanks for the amazing work.
