### ISSUE TITLE
Loading Spinner still showing after images loaded

### ISSUE THREAD

**Issue by asdutoit** [Splidejs/react-splide#41]
### Checks

- [x] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.7.5

### Description

The loading spinner is still displaying even after images have been loaded.   Or, it's possible that because Lazy loading is enabled, the spinner still displays over images further down the track that hasn't been loaded yet.   Only once all the images have been loaded does the spinner disappear. 

See the screenshot below (This React example presents a carousel with 5x images):
<img width="1261" alt="Screenshot 2022-04-26 at 10 11 31" src="https://user-images.githubusercontent.com/20240370/165253749-750b6267-e955-4601-adec-17eb54be3509.png">

<img width="1252" alt="Screenshot 2022-04-26 at 10 12 00" src="https://user-images.githubusercontent.com/20240370/165253770-ac055339-7624-43e6-924f-75ecb58ae6ce.png">

React Code:

```js
import { Splide, SplideSlide } from "@splidejs/react-splide";
import React from "react";
// import Image from "next/image";
import "@splidejs/react-splide/css";

const images = [
  "https://images.unsplash.com/photo-1590004953392-5aba2e72269a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80",
  "https://images.unsplash.com/photo-1590004845575-cc18b13d1d0a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80",
  "https://images.unsplash.com/photo-1590004987778-bece5c9adab6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80",
  "https://images.unsplash.com/photo-1590005176489-db2e714711fc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80",
  "https://images.unsplash.com/photo-1650852706530-3192c48137c6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&h=500&w=800&q=80",
];

export default function SplideCarousel() {
  return (
    <Splide
      options={{ rewind: true, lazyLoad: "nearby" }}
      aria-label="React Splide Example"
    >
      {images.map((src, idx) => (
        <SplideSlide key={idx}>
          {/* <img src={src} alt={idx} /> */}
          <img data-splide-lazy={src} alt={idx} />
          {/* <Image
            src={src}
            height={500}
            width={800}
            layout="responsive"
            className="h-full "
            alt="cover image"
            placeholder="blur"
            blurDataURL={src}
          /> */}
        </SplideSlide>
      ))}
    </Splide>
  );
}
```

### Reproduction Link

https://codesandbox.io/s/loving-archimedes-6np3qe?file=/pages/index.js

### Steps to Reproduce

1.  Create a new React or Nextjs project
2.  Create a Splide component and add the provided code (from the `Description` section)
3.  Import the Splide component into `index.js`
4.  Start server and open website

Alternatively, navigate to Codesandbox [link](https://codesandbox.io/s/loving-archimedes-6np3qe?file=/pages/index.js). 

### Expected Behaviour

The carousel should not display the spinner over images that are loaded.

**Comment by NaotoshiFujita** [comment]
The react strict mode renders your app twice, which causes the issue, I guess.
To ensure it, try disabling the strict mode.

In the production build, this will not happen.
