### ISSUE TITLE
Splide cannot be used as a JSX component

### ISSUE THREAD

**Issue by Ansaen** [Splidejs/react-splide#42]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.7.5

### Description

I am trying to implement Splide into my react/next.js project, but i get this error:

TS2786: 'Splide' cannot be used as a JSX component.   Its instance type 'Splide' is not a valid JSX element.     The types returned by 'render()' are incompatible between these types.       Type 'React.ReactNode' is not assignable to type 'import("C:/Users/ansae/IdeaProjects/web/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.         Type '{}' is not assignable to type 'ReactNode'.

```
<Splide
          className="slide-news sm:mb-20 mt-32 sm:mt-0"
          options={{
            autoplay: true,
            rewind: true,
            pauseOnHover: false,
            interval: 5000,
            pauseOnFocus: false,
          }}
        >
          <SplideSlide>
            <img
              src={getStrapiUrl(swiper.images[0].url)}
              alt={""}
              className="object-cover w-full"
            />
          </SplideSlide>
          {swiper.images?.slice(1).map((s, index) => (
            <SplideSlide key={index} className="flex w-full">
              <img
                src={getStrapiUrl(s.url)}
                alt={""}
                className="object-cover w-full"
              />
            </SplideSlide>
          ))}
        </Splide>
```

The problem is... it is still working, my page will render but because of that error i cant push it on production

### Steps to Reproduce

1. npm install @splidejs/react-splide
2. import splidejs
3. add to project
...

### Expected Behaviour

No Error

**Comment by Ansaen** [comment]
Problem with upgrading next.js

**Comment by mgonyan** [comment]
@Ansaen I am facing the same issue you had, could you please share how you solve it? thanks!

**Comment by Ansaen** [comment]
Try to downgrade next.js if that doesn´t work downgrade react-dom and react
