### ISSUE TITLE
drag free option does not work for the last element

### ISSUE THREAD

**Issue by RoMujambit** [Splidejs/react-splide#43]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.6.9 and 0.7.5

### Description

The drag free option does not work as expected and I'm not sure whether this is normal behaviour.
The last splide element always snaps back to the beginning when I try to drag it. I was assuming drag: "free" would allow me to drag it until the end.
The last element has a variable length and is sometimes longer than the container surrounding it. Is this related to the problem?

```
const splideSettings: SplideProps = {
  options: {
    rewind: false,
    autoWidth: true,
    width: '100%',
    gap: 0,
    pagination: false,
    arrows: true,
    drag: 'free',
    perMove: 1,
  },
};
```

...

```
            <Splide
              options={splideSettings.options}
              renderControls={controls}
            >
              {contentElements.map(({ href, children }, key) => {
                const isActive = key + 1 === contentElements.length;

                return (
                  <SplideSlide key={`splide ${key}`}>
                    <MyComponent key={key} href={href} isActive={isActive}>
                      {children}
                    </MyComponent>
                  </SplideSlide>
                );
              })}
              <SplideSlide />  {/* This extra SplideSlide fixes the problem for me, but I don't think it should be needed normally */}
            </Splide>
```

In order to stop the last MyComponent element from being cut off, we add an empty SplideSlide element at the end.

### Reproduction Link

https://codesandbox.io/s/frosty-leakey-vd13f8?file=/src/App.js

### Steps to Reproduce

Described above and an example can be seen on the codesandbox link.

### Expected Behaviour

Being able to drag the last element to the very end without the extra empty SplideSlide element.

**Comment by NaotoshiFujita** [comment]
It's by design. Splide does not expect slides larger than the view port and won't handle such cases, since it's not accessible.
An easy solution is setting `type` to `'loop'`.

**Comment by RoMujambit** [comment]
Ok thank you very much for your fast reply and the react-splide in general.
