### ISSUE TITLE
CSS Import does not work as described in the documentation

### ISSUE THREAD

**Issue by nathanhae** [Splidejs/react-splide#45]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

7.5.0

### Description

the documentation tells you to import CSS this way:

```
import '@splidejs/react-splide/css';
```

However, this throws an error and when I look at the package in `node_modules`, there is no top level "css" file or directory. The same issue exists in the main splide repo.

### Steps to Reproduce

1. `npm i @splidejs/react-splide`
2. add line to import css to code
3. build code

### Expected Behaviour

the CSS to be imported without errors

**Comment by NaotoshiFujita** [comment]
Those pathes are defined in [package.json](https://github.com/Splidejs/react-splide/blob/master/package.json#L57).
https://nodejs.org/api/packages.html#exports

**Comment by nathanhae** [comment]
@NaotoshiFujita I see. Have you tried this with webpack? it does not seem to be resolving these exports properly.

**Comment by NaotoshiFujita** [comment]
Then, you can directly import it from the dist directory like:
```js
import '@splidejs/splide/dist/css/splide.min.css';
```

**Comment by j10sanders** [comment]
> Then, you can directly import it from the dist directory like:
> 
> ```js
> import '@splidejs/splide/dist/css/splide.min.css';
> ```

I was unable to run jest with `import '@splidejs/react-splide/css/core'` but this fixed it for me. Thanks!
