### ISSUE TITLE
TS2307: Cannot find module '@splidejs/react-splide' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ayoubkhan558** [Splidejs/react-splide#48]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.7.8

### Description

![image](https://user-images.githubusercontent.com/99708427/180068672-154c16c2-3773-4c59-a490-972744bff58e.png)

### Expected Behaviour

It should work fine

**Comment by NaotoshiFujita** [comment]
Closing this for not enougn info.
