### ISSUE TITLE
Can't resolve '@splidejs/react-splide/css'

### ISSUE THREAD

**Issue by TonyCh55** [Splidejs/react-splide#49]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.7.8

### Description

Error when importinc css

### Steps to Reproduce

Import css

### Expected Behaviour

Without error

**Comment by NaotoshiFujita** [comment]
That means your environment can not recognize the `exports` field in the package json.
Refer to the dist file directly or configure your dev environment.
