### ISSUE TITLE
Custom arrows and pagination 

### ISSUE THREAD

**Issue by wangxingxing123654** [Splidejs/react-splide#50]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

4.x

### Description

<Splide hasTrack={ false } aria-label="...">
  <SplideTrack>
    <SplideSlide>...</SplideSlide>
  </SplideTrack>

  <div className="splide__arrows">
    <button className="splide__arrow splide__arrow--prev">Prev</button>
    <button className="splide__arrow splide__arrow--next">Next</button>
  </div>
</Splide>

not worked as expect;; as the picture beloew; the next button cannot be click

![image](https://user-images.githubusercontent.com/28847126/188859131-773a0a35-178f-44f6-9eb4-edce6b0f3c76.png)

![image](https://user-images.githubusercontent.com/28847126/188859065-7ec5543a-5ede-47d1-92b7-8b14a71fd7a5.png)

### Reproduction Link

www.xx.com

### Steps to Reproduce

 const renderProductList = () => {
    const hadProductNum = productNum > 5;
    console.log(hadProductNum,productList)
    return (
      <div
        className="product-list"
      >
         <Splide
         ref={splideRef}
         options={ {
          width : 792,
          gap   : '16px',
          perPage: 6,
          perMove: 3,
        } }
      >
          <div className="splide__arrows">
    <button className="splide__arrow splide__arrow--prev">Prev</button>
    <button className="splide__arrow splide__arrow--next">Next</button>
  </div>
       <div className="splide__arrows" />
        {productList.map((item) => {
          const { isGift, price } = activityType(item);
          return (
            <SplideSlide>
            <div key={item.id} className='product-item'>
              <div className='product-item-img'>
                <img alt={item.name} src={item.image} />
              </div>
              <div className='product-item-right'>
                <div className='size-box'>
                  <p className='size-text'>{item.options}</p>
                  <div className='size-right-price'>
                    {!isGift && (
                        <span className='amount'>
                         x{item.amount}
                        </span>
                    )}
                  </div>
                </div>
              </div>
              <div className='product-item-price-box'>
                <div className='until notranslate'>
                  <span
                    className={classnames('price', {
                      'gift-price': isGift,
                    })}
                  >
                    {price}
                  </span>
                </div>
              </div>
            </div>
            </SplideSlide>
          );
        })}
        <CustomNavigation></CustomNavigation>
        </Splide>
      </div>
    );
  };

### Expected Behaviour

the next btn does not moved , and can be click to swipe the productllist

**Comment by wangxingxing123654** [comment]
[](https://codesandbox.io/s/splide-with-breakpoints-forked-ttsqku?file=/src/Slider/index.js)
this is reproduce link

**Comment by wangxingxing123654** [comment]
https://codesandbox.io/s/splide-with-breakpoints-forked-ttsqku?file=/src/Slider/index.js

**Comment by wangxingxing123654** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/28847126/188862682-7044ee41-2932-4d74-9345-2bbe617431ff.png">

**Comment by NaotoshiFujita** [comment]
You have to use `SplideTrack` to add custom arrows.
Follow this instruction:
https://splidejs.com/integration/react-splide/#custom-structure

**Comment by wangxingxing123654** [comment]
> You have to use `SplideTrack` to add custom arrows. Follow this instruction: https://splidejs.com/integration/react-splide/#custom-structure

could you mind giving a demo  and paste it on the codesandbox ?? i believe there are so many people cannot  use SplideTrack rightly

**Comment by wangxingxing123654** [comment]
> You have to use `SplideTrack` to add custom arrows. Follow this instruction: https://splidejs.com/integration/react-splide/#custom-structure

thank u very much. it worked
