### ISSUE TITLE
Storybook - Import css from exports defined in package.json

### ISSUE THREAD

**Issue by hamzasajid1995** [Splidejs/react-splide#51]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.7.8

### Description

I'm trying to import css from Splidejs. In their Documentation they have written to import css like this: 

```import @splidejs/react-splide/css```

This way it works in the project build but does not work in storybook.
The Package.json file of Splidejs has defined exports as:

```
"exports": {
    ".": {
      "require": "./dist/js/react-splide.cjs.js",
      "import": "./dist/js/react-splide.esm.js",
      "default": "./dist/js/react-splide.esm.js"
    },
    "./css": "./dist/css/splide.min.css",
    "./css/core": "./dist/css/splide-core.min.css",
    "./css/*": "./dist/css/themes/splide-*.min.css"
  }
```

So i tried importing the above css file like this:

```import @splidejs/react-splide/dist/css/splide.min.css```

And now it works in storybook but doesn't work in project build.
My guess is that in the project build the keyword '/css/' is again replaced with what's defined in the last line of exports of splidejs/package.json.
``` "./css/*": "./dist/css/themes/splide-*.min.css"```
Which corrupts the css path.

So how can I import css from a package with respect to whats defined in exports of package.json

### Steps to Reproduce

1. Import css in storybook like this:
```import @splidejs/react-splide/css```

### Expected Behaviour

css should be able to import in storybook.

**Comment by NaotoshiFujita** [comment]
By default, Storybook uses Webpack 4 that ignores the exports field. Switch it to webpack 5:
https://storybook.js.org/blog/storybook-for-webpack-5/
