### ISSUE TITLE
Type fade not working

### ISSUE THREAD

**Issue by jimmi-rbn** [Splidejs/react-splide#54]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.7.11

### Description

Setup basic splide and add type = "fade"
Only first slide appears.

### Reproduction Link

https://codesandbox.io/s/amazing-julien-7sl1oi?file=/src/App.js

### Steps to Reproduce

Add splide
Add basic setup from demo
Add type = "fade" to options.

### Expected Behaviour

Every slide should appear

**Comment by NaotoshiFujita** [comment]
I've updated the package, and confirmed your example works with it.
Can you try the latest version (v0.7.12)?

**Comment by jimmi-rbn** [comment]
Issue resolved, thanks :)
