### ISSUE TITLE
Start doesnt start center

### ISSUE THREAD

**Issue by jimmi-rbn** [Splidejs/react-splide#55]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.7.11

### Description

Carousel doesn't align center when index is not 0

### Reproduction Link

https://codesandbox.io/s/stoic-river-wlux56?file=/src/App.js

### Steps to Reproduce

Add basic setup and add start to 1 or larger

### Expected Behaviour

Center start slide

**Comment by NaotoshiFujita** [comment]
That's because the scrollbar is shown first, and then hidden by Splide initialization.
https://github.com/Splidejs/splide/issues/712#issuecomment-1070876978
