### ISSUE TITLE
Splide track blinks on client side navigation with NextJS

### ISSUE THREAD

**Issue by Kukiezi** [Splidejs/react-splide#61]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to React Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.7.12

### Description

When navigatin between two pages in NextJS, splide element makes a blink/flicker/reload (however you wanna call it). Elements inside the track disappear and reappear causing not so nice flicker effect.

I am not sure what is causing that, since other elements on my webpage don't do this. Is there a way to prevent this from happening?

### Steps to Reproduce

1. Add a <Splide> element
2. Inside add a <SplideTrack> elements
3. Inside add a <SplideSlide>
4. Add this component in two different pages/routes
5. Navigate between them
6. Flicker is happening
...

### Expected Behaviour

When navigating client side between pages, don't flicker the splide object, but keep it in the view all the time.

**Comment by henrybabbage** [comment]
Noticing this in Safari in the latest version of Splide, in NextJS 14.0.3

**Comment by jeanniezheng** [comment]
Stilling experiencing this also in React
